### ISSUE TITLE
err is not defined

### ISSUE THREAD

**Issue by andrewlutz** [jugaldb/Node.Js-sample-project-structure#1]
https://github.com/jugaldb/Node.Js-sample-project-structure/blob/a7b2809fae12c548a6d8e399d0ff890bdb6395a9/app.js#L33

Did you mean to just hardcode a 404 here?

**Comment by jugaldb** [comment]
I did, will change it, thanks

**Comment by jugaldb** [comment]
72b26c6b3aea837344e371aadf3bf261a8381a21 

pls refer to this commit
